#!/bin/bash
#
# Print the upcoming events of orage in seven days.
declare -A WEEKDIC FREQDIC
WEEKDIC=([SU]=0 [MO]=1 [TU]=2 [WE]=3 [TH]=4 [FR]=5 [SA]=6)
FREQDIC=([DAILY]=day [WEEKLY]=week [MONTHLY]=month [YEARLY]=year [HOURLY]=hour)
ORAGE_FILE='/tmp/orage.txt'
TODO_FILE='/tmp/todo.txt'
NOW=$(date "+%Y%m%d %H:%M:%S")
TODAY=$(date +%Y%m%d)
NDAYS="7"
ENDDAY=$(date -d "7 day" +%Y%m%d)
function date_diff()
{
  local start_date=$1
  local end_date=$2
  local epoch_start=$(date -d "${start_date}" +%s)
  local epoch_end=$(date -d "${end_date}" +%s)
  case $3 in
    miniute)
      minutediff=$(( (${epoch_end}-${epoch_start})/60 ))
      ;;
    day)
      daydiff=$(( (${epoch_end}-${epoch_start})/86400 ))
      ;;
    week)
      local day=$(date -d "${start_date}" +%w)
      week_start=$(date -d "${start_date} -$day days" +%s)
      day=$(date -d "${end_date}" +%w)
      week_end=$(date -d "${end_date} -$day days" +%s)
      weekdiff=$(( (${week_end}-${week_start})/86400/7 ))
      ;;
    month)
      month_start=$(date -d "${start_date}" +%m)
      month_end=$(date -d "${end_date}" +%m)
      year_start=$(date -d "${start_date}" +%Y)
      year_end=$(date -d "${end_date}" +%Y)
      monthdiff=$(( (${year_end}-${year_start})*12+${month_end}-${month_start} ))
      ;;
    year)
      year_start=$(date -d "${start_date}" +%Y)
      year_end=$(date -d "${end_date}" +%Y)
      yeardiff=$(( ${year_end}-${year_start} ))
      ;;
  esac
}
function print_datestr()
{
  local eventday=$1
  date_diff $TODAY $eventday day
  if [ $daydiff -lt 0 ];then
    return
  elif [ $daydiff -eq 0 ];then
    datestr="TODAY "
  elif [ $daydiff -eq 1 ];  then
    datestr="TOMMORW "
  else
    datestr=${eventday:4:2}-${eventday:6:2}" "
  fi
  if [[ ${DTSTART} == *'DATE'* ]]; then #allday event
    datestr=$datestr"All-Day"
    date_diff "$NOW" "$eventday" "miniute"
  else
    event_time=${eventday:0:8}" "${STIME:9:2}":"${STIME:11:2}":"${STIME:13:2}
    datestr=$datestr${STIME:9:2}":"${STIME:11:2}
    date_diff "$NOW" "$event_time" "miniute"
  fi
  echo $minutediff"@"$datestr":"${summarys[i]}| tr -d '\r'>>$TODO_FILE
}
function cycle_byday_of_week()
{
  unset event_dates days
  IFS=',' read -r -a days <<< "$byday"
  local today=$TODAY
  local n="1"
  #echo ${days[@]:0}
  while (( ${today} <= ${ENDDAY} ));do
    weeknumber=$(date -d "${today}" +%w)
    for day in "${days[@]}";do
        if (( ${WEEKDIC[$day]} == ${weeknumber} ));then
          event_dates[$n]=${today}
          n=$(($n+1))
        fi
    done
    today=$(date -d "1 day ${today}" +%Y%m%d)
  done
  for event_date in "${event_dates[@]}";do
    if (( ${event_date} < ${TODAY} ))||(( ${event_date} > ${ENDDAY} )) \
       ||(( ${event_date} > ${end_date} ));  then
      continue
    fi
    if [ -n "$interval" ]; then
      case $freq in
        WEEKLY)
          date_diff ${STIME:0:8} ${event_date} week
          modflag=$(( ${weekdiff} % ${interval} ))
          ;;
        MONTHLY)
          date_diff ${STIME:0:8} ${event_date} month
          modflag=$(( ${monthdiff} % ${interval} ))
          ;;
        YEARLY)
          year_start=$(date -d "${STIME:0:8}" +%Y)
          year_end=$(date -d "${event_date}" +%Y)
          modflag=$(( (${year_end} - ${year_start}) % ${interval} ))
          ;;
      esac
      if (( modflag != 0 ));then
        continue
      fi
    fi
    print_datestr $event_date
   done
}
function cycle_by_time()
{
  if [ "$freq" = "DAILY" ];then
    start_date=${TODAY}
  fi
  while (( ${start_date} <= ${end_date} ));do
    if (( ${start_date} >= ${TODAY} )) && \
       (( ${start_date} < ${ENDDAY} ));then
      event_date=$start_date
      print_datestr $event_date
    fi
    start_date=$(date -d "${interval} ${FREQDIC["$freq"]} ${start_date}" +%Y%m%d)
  done
}
function periodic_event()
{
  local summary=$(echo $1| tr -d '\r')
  freq=$(echo $RRULE|grep -Eo 'FREQ=[A-Z]*'|sed 's/FREQ=//g')
  until=$(echo $RRULE|grep -Eo 'UNTIL=[0-9T]*'|sed 's/UNTIL=//g')
  byday=$(echo $RRULE|grep -Eo 'BYDAY=[A-Z,]*'|sed 's/BYDAY=//g')
  count=$(echo $RRULE|grep -Eo 'COUNT=[0-9]*'|sed 's/COUNT=//g')
  interval=$(echo $RRULE|grep -Eo 'INTERVAL=[0-9]*'|sed 's/INTERVAL=//g')
  start_date=${STIME:0:8}
  end_date=${ENDDAY}
  if [ -n "$interval" ]; then
    interval=$(($interval))
  else
    interval="1"
  fi
  if [ -n "$until" ]; then
    ul_date=${until:0:8}
    end_date=$([ $end_date -le $ul_date ] && echo $end_date||echo $ul_date)
  elif [ -n "$count" ]; then
    ninter=$(( ${interval} * (${count}-1)  ))
    if [ -n "$byday" ]; then
      end_date=$(date -d "${ninter} week ${start_date}" +%Y%m%d)
    else
      end_date=$(date -d "${ninter} ${FREQDIC["$freq"]} ${start_date}" +%Y%m%d)
    fi
  fi
  if [ -n "$byday" ]; then
    cycle_byday_of_week $summary
  else
    cycle_by_time $summary
  fi
}
function main()
{
  cat /dev/null >$TODO_FILE #clear todo file
  orage -e $ORAGE_FILE >/dev/null 2>/dev/null
  sed -i ""s/\r//"" $ORAGE_FILE
  local ind=0;
  eval $(awk -v ind="$ind" -F':' '/SUMMARY:/ {\
        print "summarys["ind"]=\x27"substr($2, 0,length($2)-1)"\x27";\
        print "lines["ind"]="FNR;ind++}' $ORAGE_FILE)
  dtstarts=($(awk -F';' '/DTSTART/ {print}' $ORAGE_FILE))
  for(( i=0;i<${#summarys[@]};i++)) do
    local sl=$((${lines[i]}+1))
    local el=$((${lines[i]}+5))
    STIME=$(echo ${dtstarts[i]} |awk -F: '{print $2}')
    RRULE=$(sed -n $sl,$el'p' $ORAGE_FILE|awk -F':' '/RRULE:/ {print $2}')
    DTSTART=${dtstarts[i]}
    if [ -n "$RRULE" ]; then
      periodic_event  ${summarys[i]}
    else
      event_date=${STIME:0:8}
      date_diff "$NOW" "$event_date" "day"
      if [ $daydiff -lt 0 ];then
        continue
      fi
      print_datestr $event_date
    fi
  done
  sort -n $TODO_FILE -o $TODO_FILE #sort events by miniute intervals
  awk -F@ '{print $2}' $TODO_FILE|head -n 15
}
main "$@"
