#!/bin/bash
#
# Print the upcoming events of orage in seven days.
declare -A WEEKDIC FREQDIC
WEEKDIC=([SU]=0 [MO]=1 [TU]=2 [WE]=3 [TH]=4 [FR]=5 [SA]=6)
FREQDIC=([DAILY]=day [WEEKLY]=week [MONTHLY]=month [YEARLY]=year [HOURLY]=hour)
ORAGE_FILE='/tmp/orage.txt'
TODO_FILE='/tmp/todo.txt'
NOW=$(date "+%Y%m%d %H:%M:%S")
TODAY=$(date +%Y%m%d)
NDAYS="7"
function getdatediff()
{
  local startdate=$(date -d "$1" +%Y-%m-%dT%H:%M:%S)
  local finaldate=$(date -d "$2" +%Y-%m-%dT%H:%M:%S)
  case $3 in
    miniute)
      minutediff=$(datediff  $startdate $finaldate -f "%M");;
    day)
      daydiff=$(datediff  $startdate $finaldate -f "%d");;
    week)
      weekdiff=$(datediff  $startdate $finaldate -f "%w");;
    month)
      monthdiff=$(datediff  $startdate $finaldate -f "%m");;
    year)
      yeardiff=$(datediff  $startdate $finaldate -f "%y");;
  esac
}
function print_datestr()
{
  local eventday=$1
  getdatediff $TODAY $eventday day
  if [ $daydiff -lt 0 ];then
    return
  elif [ $daydiff -eq 0 ];then
    datestr="TODAY "
  elif [ $daydiff -eq 1 ];  then
    datestr="TOMMORW "
  else
    datestr=${eventday:4:2}-${eventday:6:2}" "
  fi
  if [[ ${DTSTART} == *'DATE'* ]]; then #allday event
    datestr=$datestr"All-Day"
    getdatediff "$NOW" "$eventday" "miniute"
  else
    local event_time=${eventday:0:8}" "${STIME:9:2}":"${STIME:11:2}":"${STIME:13:2}
    getdatediff "$NOW" "$event_time" "miniute"
    datestr=$datestr${STIME:9:2}":"${STIME:11:2}
  fi
  echo $minutediff"@_@"$datestr":"${summarys[i]}| tr -d '\r'>>$TODO_FILE
}
function cycle_byday_of_week()
{
  unset event_dates days
  IFS=',' read -r -a days <<< "$byday"
  local today=$TODAY
  local n="1"
  #echo ${days[@]:0}
  while (( ${today} <= ${TODAY} + ${NDAYS} ));do
    weeknumber=$(date -d "${today}" +%w)
    for day in "${days[@]}";do
        if (( ${WEEKDIC[$day]} == ${weeknumber} ));then
          event_dates[$n]=${today}
          n=$(($n+1))
        fi
    done
    today=$(date -d "1 day ${today}" +%Y%m%d)
  done
  for event_date in "${event_dates[@]}";do
    if (( ${event_date} < ${TODAY} ))||(( ${event_date} > ${TODAY}+${NDAYS} )) \
       ||(( ${event_date} > ${end_date} ));  then
      continue
    fi
    if [ -n "$interval" ]; then
      case $freq in
        WEEKLY)
          day=$(date -d "${STIME:0:8}" +%w)
          week_start=$(date -d "${STIME:0:8} -$day days" +%Y%m%d)
          day=$(date -d "${event_date}" +%w)
          week_end=$(date -d "${event_date} -$day days" +%Y%m%d)
          getdatediff ${week_start} ${week_end} week
          modflag=$(( ${weekdiff} % ${interval} ))
          ;;
        MONTHLY)
          month_start=$(date -d "${STIME:0:8}" +%Y%m01)
          month_end=$(date -d "${event_date}" +%Y%m01)
          getdatediff ${month_start} ${month_end} month
          modflag=$(( ${monthdiff} % ${interval} ))
          ;;
        YEARLY)
          year_start=$(date -d "${STIME:0:8}" +%Y)
          year_end=$(date -d "${event_date}" +%Y)
          modflag=$(( (${year_end} - ${year_start}) % ${interval} ))
          ;;
      esac
      if (( modflag != 0 ));then
        continue
      fi
    fi
    print_datestr $event_date
   done

}
function cycle_by_time()
{
  while (( ${start_date} <= ${end_date} ));do
    if (( ${start_date} >= ${TODAY} )) && \
        (( ${start_date} < ${TODAY} + ${NDAYS} ));then
      event_date=$start_date
      print_datestr $event_date
    fi
    start_date=$(date -d "${interval} ${FREQDIC["$freq"]} ${start_date}" +%Y%m%d)
  done
}
function periodic_event()
{
  local summary=$(echo $1| tr -d '\r')
  freq=$(echo $RRULE|grep -Eo 'FREQ=[A-Z]*'|sed 's/FREQ=//g')
  until=$(echo $RRULE|grep -Eo 'UNTIL=[0-9T]*'|sed 's/UNTIL=//g')
  byday=$(echo $RRULE|grep -Eo 'BYDAY=[A-Z,]*'|sed 's/BYDAY=//g')
  count=$(echo $RRULE|grep -Eo 'COUNT=[0-9]*'|sed 's/COUNT=//g')
  interval=$(echo $RRULE|grep -Eo 'INTERVAL=[0-9]*'|sed 's/INTERVAL=//g')
  start_date=${STIME:0:8}
  end_date=$(date -d "+${NDAYS} days" +%Y%m%d)
  if [ -n "$interval" ]; then
    interval=$(($interval))
  else
    interval="1"
  fi
  if [ -n "$until" ]; then
    ul_date=${until:0:8}
    end_date=$([ $end_date -le $ul_date ] && echo $end_date||echo $ul_date)
  elif [ -n "$count" ]; then
    ninter=$(( ${interval} * (${count}-1)  ))
    if [ -n "$byday" ]; then
      end_date=$(date -d "${ninter} week ${start_date}" +%Y%m%d)
    else
      end_date=$(date -d "${ninter} ${FREQDIC["$freq"]} ${start_date}" +%Y%m%d)
    fi
  fi
  if [ -n "$byday" ]; then
    cycle_byday_of_week $summary
  else
    cycle_by_time $summary
  fi
}
function main()
{
  cat /dev/null >$TODO_FILE #clear todo file
  orage -e $ORAGE_FILE >/dev/null 2>/dev/null
  sed -i ""s/\r//"" $ORAGE_FILE
  ind=0;
  eval $(awk -v ind="$ind" -F':' '/SUMMARY:/ {\
        print "summarys["ind"]=\x27"substr($2, 0,length($2)-1)"\x27";\
        print "lines["ind"]="FNR;ind++}' $ORAGE_FILE)
  dtstarts=($(awk -F';' '/DTSTART/ {print}' $ORAGE_FILE))
  for(( i=0;i<${#summarys[@]};i++)) do
    local sl=$((${lines[i]}+1))
    local el=$((${lines[i]}+5))
    STIME=$(echo ${dtstarts[i]} |awk -F: '{print $2}')
    RRULE=$(sed -n $sl,$el'p' $ORAGE_FILE|awk -F':' '/RRULE:/ {print $2}')
    DTSTART=${dtstarts[i]}
    if [ -n "$RRULE" ]; then
      periodic_event  ${summarys[i]}
    else
      event_date=${STIME:0:8}
      getdatediff "$NOW" "$event_date" "day"
      if [ $daydiff -lt 0 ];then
        continue
      fi
      print_datestr $event_date
    fi
  done
  sort -n $TODO_FILE -o $TODO_FILE #sort events by miniute intervals
  awk -F@_@ '{print $2}' $TODO_FILE|head -n 5
}
main "$@"
