#!/bin/bash
oragefile='/tmp/orage.txt'
todo='/tmp/todo.txt'
orage -e $oragefile >/dev/null 2>/dev/null
sed -i ""s/\r//"" $oragefile
summary=($(awk -F: '/SUMMARY:/ {print $2}' $oragefile))
loc=($(awk -F: '/LOCATION:/ {print $2}' $oragefile))
dts=($(awk -F';' '/DTSTART/ {print}' $oragefile))
cat /dev/null >$todo #clear todo file
for(( i=0;i<${#summary[@]};i++)) do
  n=`expr $i + 1`
  time=`echo ${dts[i]} |awk -F: '{print $2}'`
  date_event=${time:0:8}
  epoch_event=`date -d "$date_event" +%s`
  today=`date +%Y%m%d`
  epoch_now=`date  -d "$today"  +%s`
  #calculate the hour intervals between today and event date
  hourintervals=$((($epoch_event - $epoch_now)/86400))
  #echo $hourDiff $date_event $time
  if [ $hourintervals -lt 0 ] #expire
  then
    continue
  elif [ $hourintervals -eq 0 ]
  then
    date="Today "
  elif [ $hourintervals -eq 1 ]
  then
    date="Tomorrow "
  else
    year=${time:0:4}
    month=${time:4:2}
    day=${time:6:2}
    date=$month'-'$day
  fi
  if [[ ${dts[i]} == *'DATE'* ]]
  then #allday event
    date=$date
  else
    hour=${time:9:2}
    min=${time:11:2}
    date=$date$hour':'$min
  fi
  echo $hourintervals'@_@'$date':'${summary[i]}| tr -d '\r'>>$todo
done;
sort -n $todo -o $todo #sort events by hour intervals
awk -F@_@ '{print $2}' $todo|head -n 5
